[project]
authors = ["Martin Fleischmann <martin@martinfleischmann.net>"]
channels = ["conda-forge"]
description = "A course on spatial data science in Python"
name = "sds"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
esda = ">=2.6"
geopandas = ">=1.0"
libpysal = ">=4.12.0"
mgwr = ">=2.2"
pandas = ">=2.2"
pyarrow = ">=17"
pyogrio = ">=0.9"
scikit-learn = "*"
seaborn = ">=0.13"
statsmodels = ">=0.14"
ipykernel = "*"
jupyter-cache = "*"
jupyterlab = "*"
